# Note! If you're using jekyll serve --watch to run a server, you'll need to restart after any changes here
name: "Twenty-Two"
description: "A blog to capture the jounery of my life after university."
baseurl: "/Blossoms"
#excerpt_separator: "<!--more-->"

owner: "Your Name"
email: "foo@bar.com"
twitter: "techieshark"
github: "user.name"
facebook: "user.name"
# the following really long number is what you find in https://plus.google.com/your-really-long-id/posts
googleplus: 111111111111111111
location: |
    1234 Somewhere Road
    Nashville, TN 00000
    USA
phone: 555-555-5555
skype: your.username
